---
- name: Install haproxy
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Configure haproxy
  ansible.builtin.template:
    src: "{{ inventory_dir }}/templates/haproxy.cfg.j2"
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0644"
  notify: Reload haproxy

- name: Insert Let's Encrypt CA certificate for HAProxy to use
  ansible.builtin.copy:
    src: letsencrypt-ca.pem
    dest: /etc/haproxy/letsencrypt-ca.pem
    owner: root
    group: root
    mode: "0644"

- name: Ensure haproxy is started
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true
